default:
  #image: continuumio/anaconda3:latest
  image: registry.hzdr.de/multiscale-wdm/surrogate-models/fesl/fesl

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  APT_CACHE_DIR: "$CI_PROJECT_DIR/apt"

cache:
  paths:
    - .cache/pip
    - apt
  key: ${CI_JOB_STAGE}

stages:
  - build
  - test
  - deploy

.module_setup: &module_setup
    #- apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -q -y gcc g++ python3-dev libz-dev swig git-lfs && apt-get clean
    - cd ../
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.hzdr.de/multiscale-wdm/surrogate-models/fesl/data  fesl_data_repo
    - cd fesl_data_repo
    - git lfs install
    - bash ../fesl/install/data_repo_link/link_data_repo.sh `pwd`
    - cd ../
    - cd fesl
    - pip install -r requirements.txt
    - pip install -e .
    - pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

setup-fesl:
  stage: build
  before_script:
    - pip cache list
    - pip cache dir
    - *module_setup
    - pip cache list
  script:
    - python3 examples/ex00_verify_installation.py
#  after_script:
  only:
    - master
    - improve-CI
    - pipelinetest

setup-docs:
  stage: build
  script:
    - echo "Docs setup."

test-basic-functions:
  stage: test
  script:
    - pip cache list
    - *module_setup
    - pip cache list
    - cd test
    - python3 fesl_tests.py
    - cd ..
  needs: [setup-fesl]
  only:
    - master
    - improve-CI
#    - pipelinetest

test-workflow:
  stage: test
  script:
    - pip cache list
    - *module_setup
    - pip cache list
    - cd examples
    - python3 ex99_verify_all_examples.py
    - cd ..
  needs: [setup-fesl]
  only:
    - master
    - improve-CI
#    - pipelinetest

test-docstrings:
  stage: test
  before_script:
    - pip --version
    - pip cache list
    - pip install -qU pip
    - pip install -qU pydocstyle
  script:
    - pydocstyle --convention=numpy fesl
  needs: [setup-docs]
  only:
    - master
    - improve-CI
    - documentation
    - fix_docstrings
    - /^fix_docstrings_in_.*$/

pages:
  stage: deploy
  before_script:
  - pip --version
  - pip cache list
  - pip cache dir
  - pip install -qU pip
  - pip install -qU sphinx
  - pip install -qU sphinx_rtd_theme
  - pip install -qU recommonmark
  - pip cache list
  script:
  - sphinx-apidoc -o docs/source/api fesl
  - sphinx-build -b html -d docs/_build/doctrees docs/source docs/_build/html
  after_script:
  - mv docs/_build/html public
  needs: [test-docstrings]
  artifacts:
    paths:
    - public
  when:
    always
  only:
  - master
  - improve-CI
  - documentation
  - fix_docstrings
  - /^fix_docstrings_in_.*$/
