name: mala-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alembic=1.7.6
  - ase=3.22.1
  - async-timeout=4.0.2
  - attrs=21.4.0
  - autopage=0.5.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=5.0.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.0.3
  - cliff=3.10.0
  - cmaes=0.8.2
  - cmd2=2.3.3
  - colorama=0.4.4
  - colorlog=6.6.0
  - cryptography=36.0.1
  - cycler=0.11.0
  - flask=2.0.3
  - fonttools=4.29.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - frozenlist=1.3.0
  - future=0.18.2
  - giflib=5.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - greenlet=1.1.2
  - grpcio=1.43.0
  - idna=3.3
  - importlib-metadata=4.11.0
  - importlib_resources=5.4.0
  - itsdangerous=2.0.1
  - jbig=2.1
  - jinja2=3.0.3
  - jpeg=9e
  - kiwisolver=1.3.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libimagequant=2.17.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - mako=1.1.6
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib-base=3.5.1
  - mkl=2022.0.1
  - mpmath=1.2.1
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.3
  - ninja=1.10.2
  - numpy=1.22.2
  - oauthlib=3.2.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - optuna=2.10.0
  - packaging=21.3
  - pandas=1.4.1
  - pbr=5.8.1
  - pillow=9.0.1
  - pip=22.0.3
  - prettytable=3.1.0
  - protobuf=3.19.4
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyperclip=1.8.2
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.10.2
  - pytorch-cpu=1.10.2
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - readline=8.1
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scipy=1.8.0
  - setuptools=59.5.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlalchemy=1.4.31
  - sqlite=3.37.0
  - stevedore=3.5.0
  - tbb=2021.5.0
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.11
  - tqdm=4.62.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - werkzeug=2.0.3
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
